Repository microsoft/azure-pipelines-extensions, pull requests merged in 2023-09, with the labels that each got.

#1188 ExternalTFS: Stable version which downloads artifacts
  Extensions/ExternalTfs/Src/Tasks/DownloadArtifactsTfsGit/downloadTfGit.js
  Extensions/ExternalTfs/Src/Tasks/DownloadArtifactsTfsGit/task.json
  Extensions/ExternalTfs/Src/Tasks/DownloadArtifactsTfsVersionControl/task.json
  Extensions/ExternalTfs/Src/Tasks/DownloadExternalBuildArtifacts/task.json
  Extensions/ExternalTfs/Src/Tasks/DownloadExternalBuildArtifacts/task.loc.json
  Extensions/ExternalTfs/Src/vss-extension.json
Labels: Area:RM

#1189 Replaced scp2-2022 library with ssh2-sftp-client
  Extensions/Ansible/Src/Tasks/Ansible/ansibleRemoteMachineInterface.ts
  Extensions/Ansible/Src/Tasks/Ansible/ansibleUtils.ts
  Extensions/Ansible/Src/Tasks/Ansible/package-lock.json
  Extensions/Ansible/Src/Tasks/Ansible/package.json
  Extensions/Ansible/Src/Tasks/Ansible/task.json
  Extensions/Ansible/Src/vss-extension.json
Labels: Area:RM, Improvement

#1192 Fixed missing arguments bug
  Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/IISWebAppDeployV1/MsDeployOnTargetMachines.ps1
  Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/IISWebAppDeployV1/task.json
  Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/IISWebAppDeployV2/MsDeployOnTargetMachines.ps1
  Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/IISWebAppDeployV2/task.json
  Extensions/IISWebAppDeploy/Src/vss-extension.json
Labels: bug, Area: IISWebAppDeploy

#1193 Add release pipeline for IIS Web App Deployment Using WinRM
  .github/workflows/release-iiswebapp.yml
Labels: enhancement, Area: IISWebAppDeploy, Improvement
